[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 15

[window]
opacity = 0.7

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[cursor.style]
shape = "Block"
blinking = "On"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "T"
mods = "Shift"
command = { program = "tmux", args = ["new-session", "-A", "-s", "main"] }

[terminal.shell]
program = "/usr/bin/zsh"

[colors.primary]
background = "0x1a1b26"
foreground = "0xc8c093"

[colors.cursor]
text = "0x1a1b26"
cursor = "0xc8c093"

[colors.normal]
black = "0x1a1b26"
red = "0xc34043"
green = "0x76946a"
yellow = "0xc0a36e"
blue = "0x7e9cd8"
magenta = "0x957fb8"
cyan = "0x6a9589"
white = "0xc8c093"

[colors.bright]
black = "0x4e5173"
red = "0xc34043"
green = "0x76946a"
yellow = "0xc0a36e"
blue = "0x7e9cd8"
magenta = "0x957fb8"
cyan = "0x6a9589"
white = "0xc8c093"
